"""baseline

Revision ID: 51a8a4379d41
Revises: 
Create Date: 2026-08-31 06:47:33.385382
"""
from alembic import op
import sqlalchemy as sa


revision = '51a8a4379d41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.String(length=10), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('backdrop_path', sa.String(length=255), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('studio', sa.Text(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('folder_path', sa.String(length=1024), nullable=True),
    sa.Column('file_status', sa.String(length=50), nullable=False),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('edition', sa.String(length=255), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('collection_name', sa.String(length=255), nullable=True),
    sa.Column('do_rename', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'tmdb_id')
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('rss_feeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'url')
    )
    with op.batch_alter_table('rss_feeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rss_feeds_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('shows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('tvdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('metadata_source', sa.String(length=10), nullable=False),
    sa.Column('tvdb_season_type', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('backdrop_path', sa.String(length=255), nullable=True),
    sa.Column('folder_path', sa.String(length=1024), nullable=True),
    sa.Column('season_format', sa.String(length=255), nullable=False),
    sa.Column('episode_format', sa.String(length=255), nullable=False),
    sa.Column('do_rename', sa.Boolean(), nullable=False),
    sa.Column('do_missing', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('first_air_date', sa.String(length=10), nullable=True),
    sa.Column('number_of_seasons', sa.Integer(), nullable=False),
    sa.Column('number_of_episodes', sa.Integer(), nullable=False),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('networks', sa.Text(), nullable=True),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('next_episode_air_date', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'tmdb_id')
    )
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shows_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('air_date', sa.String(length=10), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('still_path', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('file_status', sa.String(length=50), nullable=False),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episodes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('library_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('dest_path', sa.String(length=1024), nullable=True),
    sa.Column('show_name', sa.String(length=255), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('episode_code', sa.String(length=20), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('movie_title', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_log_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('scan_folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('folder_type', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'path')
    )
    with op.batch_alter_table('scan_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_folders_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('watcher_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('show_name', sa.String(length=255), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('episode_code', sa.String(length=20), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('movie_title', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watcher_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watcher_log_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ignored_episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id')
    )
    with op.batch_alter_table('ignored_episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ignored_episodes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pending_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=False),
    sa.Column('dest_path', sa.String(length=1024), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_actions_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_actions_tenant_id'))

    op.drop_table('pending_actions')
    with op.batch_alter_table('ignored_episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ignored_episodes_tenant_id'))

    op.drop_table('ignored_episodes')
    with op.batch_alter_table('watcher_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watcher_log_tenant_id'))

    op.drop_table('watcher_log')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('scan_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_folders_tenant_id'))

    op.drop_table('scan_folders')
    with op.batch_alter_table('library_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_log_tenant_id'))

    op.drop_table('library_log')
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episodes_tenant_id'))

    op.drop_table('episodes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))

    op.drop_table('users')
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shows_tenant_id'))

    op.drop_table('shows')
    with op.batch_alter_table('rss_feeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rss_feeds_tenant_id'))

    op.drop_table('rss_feeds')
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movies_tenant_id'))

    op.drop_table('movies')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_tenant_id'))

    op.drop_table('app_settings')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_tenant_id'))

    op.drop_table('agents')
    op.drop_table('tenants')
    # ### end Alembic commands ###
